[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs-18_x"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-scripts",
    "npm install",
    "npm run build"
]

[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache",
    "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "sh -c 'php artisan migrate:fresh --force --seed && php artisan serve --host=0.0.0.0 --port=$PORT'"
